services:

  mysql:
    image: mysql:8.4.0
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=compare
    ports:
      - 3306:3306

  rabbitmq:
    image: rabbitmq:4.0.5-management
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:7.4.1
    ports:
      - 6379:6379
